### PR TITLE
Add status code in HttpError exception log

### PR DESCRIPTION
**Pull request by onevirus**
This should take care of #310 

Sadly, gcs does not include message in many responses.
So, I add status code at the end of exception log.

@martindurant 
I did only _call non-retriable exception case.
Let me know if you want retriable exception case also.

### CODE REVIEW

**Comment by martindurant** [comment]
Yes, I would vote to log both the code and message, if we have them, in every case.

**Comment by onevirus** [comment]
@martindurant 
I added error code on every HttpError logs.

**Comment by martindurant** [comment]
How about the following, which makes for simpler code, and ensures the code and the message is included every time?
```diff
--- a/gcsfs/utils.py
+++ b/gcsfs/utils.py
@@ -7,8 +7,10 @@ class HttpError(Exception):

     def __init__(self, error_response=None):
         if error_response:
-            self.message = error_response.get("message", "")
             self.code = error_response.get("code", None)
+            self.message = error_response.get("message", "")
+            if self.code:
+                self.message += ", %s" % self.code
         else:
             self.message = ""
```

**Comment by martindurant** [comment]
Perfect!

**Pull request merged**
