### PR TITLE
Add pyarrow hook to dask shim

### PR DESCRIPTION
**Pull request by martindurant**
Fixes https://github.com/dask/dask/issues/4009

(copies code from fsspec - could have been implemented in pyarrow, or by adapting gcsfs to be a subclass of fsspec)

### CODE REVIEW

**Comment by mrocklin** [comment]
I take it that there is some code elsewhere that looks for that special method name?

**Comment by martindurant** [comment]
Here: https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet.py#L675 (i.e., our own code) - so this is one of those cases I would like to see refactored.

**Comment by martindurant** [comment]
May find this interesting: https://github.com/martindurant/filesystem_spec/pull/16/commits/92eff11cd85d82b1244210e8fc8ebe6c18185d5d

**Comment by martindurant** [comment]
ping @cdagnino , have you had a chance to check this for your use case yet?

**Pull request merged**
