### PR TITLE
metadata on resumable creation

### PR DESCRIPTION
**Pull request by yiga2**

### CODE REVIEW

**Comment by martindurant** [comment]
Please merge following #37 , which fixes the `forced` order and code 502.

**Comment by yiga2** [comment]
My bad - my repo was not in sync.
Done.

**Comment by martindurant** [comment]
OK, I can merge this, since it's very unobtrusive, but I would like to see a follow up PR with the other parts I mentioned, as well as tests.

**Comment by yiga2** [comment]
Will do - I have a need for setting metadata on existing objects too. 
For now I use `gsutil setmeta` but interestingly it has a batch option to set in bulk. I will check its code to get inspired for the same here.
Thanks @martindurant, my first merge ! (am only a coder by trade)

**Pull request merged**
