### PR TITLE
Random Cleanups

### PR DESCRIPTION
**Pull request by nbren12**
hi @martindurant. I cleaned up the GCSFileSystem class a bit. Do you think
these refactors are helpful?

Changes
- delete unused (?) gcsfs.auth.py module
- refactor auth related logic to a new class GoogleCredentials
- cleanup the implementation of GCSFileSystem._request

### CODE REVIEW

**Comment by martindurant** [comment]
This looks good at a quick glance, I'll try to get around to a thorough review soon.

**Comment by nbren12** [comment]
Sure thing. Take your time.

**Comment by martindurant** [comment]
Sorry, conflict here following the retries PR. I suspect you would be friendly with those changes.

**Comment by nbren12** [comment]
For sure. I saw that coming ;). I can rework this one.

**Comment by nbren12** [comment]
This is ready for review @martindurant.

**Pull request merged**
