### PR TITLE
Add auth scopes

### PR DESCRIPTION
**Pull request by martindurant**
Perhaps solves some auth problems as shown in #83

### CODE REVIEW

**Comment by bnaul** [comment]
I was about to make almost exactly the same PR 😄 . The `google.cloud.storage` client does this as
```
SCOPE = ('https://www.googleapis.com/auth/devstorage.full_control',
         'https://www.googleapis.com/auth/devstorage.read_only',
         'https://www.googleapis.com/auth/devstorage.read_write')

credentials, _ = google.auth.default()
self._credentials = google.auth.credentials.with_scopes_if_required(credentials, SCOPE)
```
I assume they're equivalent but figured I'd share what I was going with just in case there's any subtle difference...

**Comment by martindurant** [comment]
Have you had a chance to use the two methods to see if there is a difference, @bnaul ? Since I've never had any problem gaining credentials...

**Comment by bnaul** [comment]
Both seem to work fine for me; this is running on a k8s pod where the service account has permissions to read/write to a bucket but the node doesn't have any special storage scopes. With the current master I see the same scope issues that have been reported but this resolves it.

**Comment by martindurant** [comment]
OK, excellent - thanks @bnaul

**Pull request merged**
