### PR TITLE
Fix `copy` when `done` is not True

### PR DESCRIPTION
**Pull request by sdanzan**
The code:
```
while out.json()['done'] is not True:
    out = self._call(
        'POST', 'b/{}/o/{}/rewriteTo/b/{}/o/{}', b1, k1, b2, k2,
        rewriteToken=out['rewriteToken'], destinationPredefinedAcl=acl)
```
Doesn't work due to `out` being a request response and `rewriteToken` being a field of the corresponding JSON representation.
This simple fix just chains `.json()` after `_call(...)`.

### CODE REVIEW

**Comment by martindurant** [comment]
Yes, you are right - thank you. Don't worry about the CI test failures, I'll have to sort that out at some point. Did all tests pass for you locally?

**Comment by sdanzan** [comment]
`test_pickle` ans `test_map_pickle` are failing but it seems to be for unrelated reasons.

**Comment by martindurant** [comment]
Please merge from master, should fix things

**Comment by TomAugspurger** [comment]
Merged master. Merging when CI passes.

**Comment by TomAugspurger** [comment]
Thanks @sdanzan!

**Pull request merged**
