### PR TITLE
Add metadata methods

### PR DESCRIPTION
**Pull request by martindurant**
Fixes https://github.com/dask/gcsfs/issues/38

### CODE REVIEW

**Comment by martindurant** [comment]
(tests not created, recordings not updated)

**Comment by martindurant** [comment]
@yiga2 , a quick implementation that seems to work

**Comment by martindurant** [comment]
@yiga2 , you are welcome to play with this before I merge

**Comment by yiga2** [comment]
@martindurant I did - works fine ! Tested the `put` too. 

Unless no need to hold off, may want to bundle with another (unrelated) change - if applicable - as per my comment [here](https://github.com/dask/gcsfs/issues/12#issuecomment-437725658)

**Pull request merged**
