### PR TITLE
Fix small file upload

### LINKED ISSUE #70: Small file upload fails
```
In [5]: import pandas as pd
   ...: import dask.dataframe as dd
   ...: dd.from_pandas(pd.DataFrame({'x': [1]}), npartitions=1).to_csv(f'gs://{bucket}/test.csv')
   ...:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/miniconda3/envs/model/lib/python3.6/site-packages/gcsfs/core.py in flush(self, force)
    905         if self.location is not None:
--> 906             self._upload_chunk(final=force)
    907         if force:

~/miniconda3/envs/model/lib/python3.6/site-packages/gcsfs/core.py in _upload_chunk(self, final)
    930             headers=head, data=data)
--> 931         validate_response(r, self.location)
    932         if 'Range' in r.headers:

~/miniconda3/envs/model/lib/python3.6/site-packages/gcsfs/core.py in validate_response(r, path)
    131         else:
--> 132             raise RuntimeError(m)
    133

RuntimeError: b"Invalid request.  The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144).  The received request contained 7 bytes, which does not meet this requirement."
```

The same behavior happens with a simple string write:
```
In [8]: with gcsfs.GCSFileSystem(project=project).open(f'{bucket}/test.txt', 'w') as f:
   ...:     f.write('test')
...
RuntimeError: b"Invalid request.  The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144).  The received request contained 4 bytes, which does not meet this requirement."
```

But weirdly enough, changing the write type to binary resolves this:
```
In [9]: with gcsfs.GCSFileSystem(project='model-streetlight-toronto').open('persona-upload/test.txt', 'wb') as f:
   ...:     f.write(b'test')
   ...:
In [10]:  # OK
```

I'm trying to remember off the top of my head if this is new behavior but I'm not sure.
```
gcsfs==0.0.4
google-cloud-storage==1.7.0
```

### PR DESCRIPTION
**Pull request by martindurant**
(see a slightly different version in
https://github.com/dask/gcsfs/commit/30be23c53debaf42d89787633f68f6a8c2c855be )

Fixes #70 

cc @asford

### CODE REVIEW

**Comment by asford** [comment]
Sorry, but it may take me until later in the day to review this. Would you be open to a cherry-pick of 30be23c with the constant definitions and warning logic on small flushes? I found that *somewhat* surprising while I was debugging this issue.

**Comment by martindurant** [comment]
I'm afraid the cherry-pick is not easy at all, because of the other changes it's folded in with (not least the logging/tracing logic).

**Comment by asford** [comment]
I split that commit to remove the trace/logging changes if you're open to it. I just want to make sure you'd be open to that alternate before I do the work. At the very least I'd like to see the constant refactoring; I had trouble groking the current behavior until I lifted the constants out.

**Comment by martindurant** [comment]
OK, @asford , I'll try with your lines of code. I am taking the rest of today off sick, though, so I'm not sure when I'll get to it.

**Comment by asford** [comment]
No problem, would you like me to do the cherry-pick today?

**Comment by martindurant** [comment]
Sure, if you feel like it.

**Comment by martindurant** [comment]
Superseded by #73

**Pull request closed without merging**
