### PR TITLE
All HTTP calls through a session

### PR DESCRIPTION
**Pull request by martindurant**
One requests.Session per GCSFileSystem instance. Should cut down on SSL handshaking.

### CODE REVIEW

**Comment by martindurant** [comment]
Fixes #50

**Comment by martindurant** [comment]
Q: would it be better to have a single global Session for everything? In typical dask usage, I think we may be creating new GCSFileSystem instances, which would have new sessions and not benefit from sharing.

**Comment by mrocklin** [comment]
If the different GCSFileSystem objects had different permission would they want different Sessions?

Alternatively, perhaps we should have a singleton `GCSFileSystem.current()`?

**Comment by martindurant** [comment]
No, we can still maintain a different header token - which fixes the user identity - for each file-system instance rather than have it set for the global session. The SSL connection should still be sharable between them, the interchange of certificates does not depend on the user token.

**Comment by mrocklin** [comment]
I'm inclined to merge this for now and then, once we hit performance issues with many file systems resolve that later, perhaps by caching file system objects.

**Comment by martindurant** [comment]
Agreed.

**Pull request merged**
