### PR TITLE
Add size and md5 consistency

### LINKED ISSUE #18: Check file consistency on write
GCS provides size and md5 hash information on written files. At the minimum, the former should be checked against the expected upload size, and optionally the md5 also for a stronger guarantee.

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #18 

What should be the default option?

Any need for crc32 check as another option? (I suppose its a bit faster than md5)

### CODE REVIEW

**Comment by martindurant** [comment]
Note that I cannot easily think of a way to induce a consistency failure: perhaps injecting spurious data into the md5 hash object?

Also note that, unlike failures on individual REST calls, a consistency failure is not retriable.

@mrocklin - this, together with retries, would hopefully have avoided, or at least exposed, problems with the massive data transfer you were running.

**Comment by mrocklin** [comment]
I take it that google is calling md5 and crc32 and such on their end?

I don't have strong thoughts on what the default should be.  How fast is crc32?

**Comment by martindurant** [comment]
Yes, google supplies md5 and crc32 on each file when the upload is complete.
A quick test in a console shows the two to be the same speed (~1GB/s for me), which is a little surprising.

**Comment by mrocklin** [comment]
Doing a consistency check by default seems like the right choice to me

**Comment by mrocklin** [comment]
FWIW I would go for something more intense than size.  I would expect google network to max out around 1-200MB/s, which, given your numbers, means 20% or so of a CPU core.  I think that that is a reasonable sacrifice for default behavior.

**Pull request merged**
