### PR TITLE
Allow large uploads by limiting the chunk size

### PR DESCRIPTION
**Pull request by agrinh**
An intended fix for #325 

Instead of the suggestion from #325 of creating a loop in `_upload_chunk` I use the existing method for handling shortfall. Let me know whether you think this is a good approach.

Seems to work when I'm testing this manually, but the added test locks on verifying the contents (`gcsfs.cat`). I haven't figured out why, but if you have any ideas I'd appreciate it.

### CODE REVIEW

**Comment by martindurant** [comment]
This PR is failing because the new test function doesn't not have a vcrpy recording - see the project documentation on how to create one. I think, though, that for the sake of the test you should temporarily decrease the maximum upload size by a lot, since all that data gets recorded into the repo - indeed, what is reasonable for a single HTTP operation?

**Comment by martindurant** [comment]
@agrinh , I have had a go at reworking this. Please see if it solves your problem! Note that there were errors in your version, around whether the large upload was the last write for the file or not. I think everything is fixed, but I have strange connection problems to GCS right now, so I wasn't able to record a run for the test function, which is skipped for now.

**Comment by agrinh** [comment]
@martindurant awesome, thanks! Sorry for the late reply, but I'll have a look this weekend.

**Comment by agrinh** [comment]
@martindurant I think I got it working now, simplified some logic and made sure to clear the buffer and update offset when done, but I'm seeing something really weird. If the upper limit is set to a power of 2, the test works fine, but whenever it is set to something else (like the limit you chose, `10 * 2 ** 20`), the test freezes on the second PUT (with or without my changes). I really can't figure this out, would you have time to take a look? For now, I changed the the upper limit in the test to a power of 2.

Finally, all other tests seem OK except for:
```
ERROR    gcsfs:core.py:555 _call non-retriable exception: You already own this bucket. Please select another name., 409
Traceback (most recent call last):
  File "~/proj/gcsfs/gcsfs/core.py", line 538, in _call
    self.validate_response(status, contents, json, path, headers)
  File "~/proj/gcsfs/gcsfs/core.py", line 1326, in validate_response
    raise HttpError(error)
gcsfs.utils.HttpError: You already own this bucket. Please select another name., 409
```

How should I handle this?

**Comment by martindurant** [comment]
The hang and power-of-two is pretty odd, I'll try to look. 
The error about owning the bucket is fine and can be ignored, no tests should fail because of it.
However, several tests here do fail via VCR, which means that the calls made by the code must have changed, which was not supposed to happen for files smaller than the limit.

**Comment by agrinh** [comment]
@martindurant Feels like something is off with my test environment. When I try running setting the vcr record mode to `"once"` or `"none"` locally after `"all"`, the tests fail from `test_simple`. I tried reverting all recordings and skipping the large upload test that seems to have made the tests happy in the CI (doesn't work locally). Any chance that you could have another try at running the tests, I'm finding it really difficult to debug.

**Comment by martindurant** [comment]
It was not your build system, but timeouts caused by vcrpy attempting to work with large(ish) recordings, and causing some internal timeout. Hoping this will work.

**Comment by agrinh** [comment]
@martindurant great, thanks!

**Comment by kconvey** [comment]
@martindurant Any idea when this might be included in a release?

**Comment by martindurant** [comment]
Soon... I am working through some stuff in fsspec around event loops that might affect gcsfs, so after that is done.

**Pull request merged**
