### PR TITLE
reorder force flush condition + add 502 as retriable error

### LINKED ISSUE #31: does not handle 502 errors (returned by GCS when server is overloaded)
I have faced several times the same 502 error when writing in chunks. Errors are sporadic and look like:
```
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 896, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 868, in close
    self.flush(force=True)
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 755, in flush
    self._upload_chunk(final=force)
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 777, in _upload_chunk
    validate_response(r, self.location)
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 111, in validate_response
    raise RuntimeError(m)
RuntimeError: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That's an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That's all we know.</ins>

Exception ValueError: ValueError('Force flush cannot be called more than once',) in <bound method GCSFile.__del__ of <GCSFile tempfile.txt>> ignored
```
Google writes this may happen when system/network is under stress - our script does indeed read and write from `GCS` several GB of files in chunks after on-the-fly transformations.
Look at `Handling Errors` at https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload.
They indicate to implement `exponential-backoff`: https://cloud.google.com/storage/docs/exponential-backoff

Is this something that can be implemented in `GCSFS` i.e. resubmit a chunk when such `5xx` error occurs ?

If not, wrapping the write statement in a try/exception, delete the target file written so far and reprocess is not an option for me. Because the records I write are based off data in a compressed `GCSFS`-file I read. ZipFileExt are not seekable so what is read is gone. I would have to delete the whole batch and restart.

### PR DESCRIPTION
**Pull request by yiga2**
- fixes #31 
- add error code 502 as retriable error as per https://cloud.google.com/storage/docs/json_api/v1/status-codes#502_Bad_Gateway

### CODE REVIEW

**Comment by yiga2** [comment]
I think the test must be adapted

**Comment by martindurant** [comment]
Yes, the reordering did this, but I think that the logic now is essentially right, but that `write` should check for `forced=True` and raise the error there. Getting the tests to work is, in general, a bit of a pain, because they rely on vcrpy, which is rather flaky.

Sorry I haven't been able to dedicate any effort to this project. I hope to come back to it and clean up the several small-but-annoying issues.

**Comment by yiga2** [comment]
Thanks @martindurant and team for Pythonic file-object support of GCS.

Why Google has not this covered yet in their client library is beyond me. 
As a fyi, the arguments for it, lack of traction and perceived resistance: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3903

In the meantime I am researching how to use service accounts for GCSFS credentials as this fits a use case of mine.

**Comment by martindurant** [comment]
Superseded by #37

**Pull request closed without merging**
