### PR TITLE
Add check if dictionary token is service account token

### PR DESCRIPTION
**Pull request by VMois**
Related issue: #120

### CODE REVIEW

**Comment by martindurant** [comment]
I don't see why py35 should have failed where the others passed, but rerunning it just in case it's "one of those things". I don't actually case about py35 any more, can probably change the set matrix to 2.7/3.6/3.7 (and maybe even drop 2.7 in January).

**Comment by VMois** [comment]
Maybe, there is a bug or something that causes failure. On Friday, I will try to change the way dict token is checked and we will check if py35 will fail.

**Comment by VMois** [comment]
I think my code is causing an error. I have tested this version and another way of checking dict object. Version where I'm using checking in `_dict_to_credentials` is failing, but another part where I;m checking inside `_connect_token` is passing all the tests. This is a code bad version code:
```python
    def _dict_to_credentials(self, token):
        try:
            token = service_account.Credentials.from_service_account_info(
                token, scopes=[self.scope])
        except:
            token = Credentials(
                None, refresh_token=token['refresh_token'],
                client_secret=token['client_secret'],
                client_id=token['client_id'],
                token_uri='https://www.googleapis.com/oauth2/v4/token',
                scopes=[self.scope]
            )
        return token
```

For now, I will put dict check to `_connect_token`, but I don't know if it's good solution. Maybe, it's better to figure out how to fix above code. Any thoughts @mrocklin ?

**Comment by martindurant** [comment]
Are you able to run the failing test on py35 with real credentials? It may just be vcrpy funniness See the settings.py file for the env vars you need to set. Whether the service creds check happens in the token making method or where it gets applied shouldn't matter as far as I can tell.

**Comment by VMois** [comment]
@martindurant Sorry for late response. On real credentials py3.5 (using GCSFS_RECORD_MODE=all ) the failing test is successful. 

P.S It's not related to this issue, but when I have changed  GCSFS_RECORD_MODE=once, *test_ls2* is failed. Traceback:
```
@my_vcr.use_cassette(match=['all'])
    def test_ls2(token_restore):
        with gcs_maker() as gcs:
>           assert TEST_BUCKET in gcs.ls('')
E           AssertionError: assert 'dask-test-run' in ['anaconda-enterprise', 'anaconda-public-data', 'artifacts.test_project.appspot.com', 'test_project_cloudbuild', 'dataflow-anaconda-compute', 'gcsfs-testing', ...]
```

**Comment by martindurant** [comment]
I wouldn't worry about that failure, you seem to be getting the recorded values (i.e., things that make sense on my system).

**Comment by martindurant** [comment]
OK, merging this now. I don't care about py35 any more, and it seems travis does not yet support 37, it seems, so this will do for now.
Thanks for handling things.

**Comment by alimanfoo** [comment]
FWIW Travis does support python 3.7 but needs some tweaks to config, see
e.g. .travis.yml in numcodecs.

**Comment by martindurant** [comment]
Thanks, I'll look it up for next time, when the current google client key will be expiring

**Pull request merged**
