### PR TITLE
use versioneer

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks!  I appreciate this.

**Comment by martindurant** [comment]
Does this look correct?

**Comment by mrocklin** [comment]
Operationally it seems to work well :)

```python
In [1]: import gcsfs

In [2]: gcsfs.__version__
Out[2]: '0.0.5+6.g69fbff0'
```

I don't know why, but Dask also has the following line in setup.py

          cmdclass=versioneer.get_cmdclass(),

**Comment by martindurant** [comment]
As far as I understood, that it only required if the package has associated executable scripts.

**Comment by mrocklin** [comment]
gcsfuse?

**Comment by martindurant** [comment]
That's a good point :)

**Pull request merged**
